"""add chef_name and chef_phone to kitchens

Revision ID: fb25b2fe1a87
Revises: 
Create Date: 2026-04-27 00:31:26.002408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb25b2fe1a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chef_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('chef_phone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)

    with op.batch_alter_table('kitchens', schema=None) as batch_op:
        batch_op.drop_column('chef_phone')
        batch_op.drop_column('chef_name')

    # ### end Alembic commands ###
